import { Poppins } from "next/font/google";
import "./globals.css";
import SidebarWrapper from "@/components/sidebar/SidebarWrapper"; // Import the wrapper
import { DatabaseProvider } from "@/context/DatabaseContext";
import { ThemeProvider } from "next-themes";
import AuthGuard from "@/components/authGuard/AuthGuard";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Notion Fuse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`} suppressHydrationWarning>
      <body 
        className="h-screen font-sans flex overflow-hidden dark:bg-gray-950" 
        style={{ fontFamily: 'var(--font-poppins)' }}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthGuard>
            <DatabaseProvider>
              {/* Replace the static SideBar with the conditional Wrapper */}
              <SidebarWrapper /> 
              
              <main className="flex-1 overflow-y-auto bg-gray-50 dark:bg-gray-950">
                {children}
              </main>
            </DatabaseProvider>
          </AuthGuard>
        </ThemeProvider>
      </body>
    </html>
  );
}